---
title: "exercise2"
output: html_document
date: '2022-04-22'
---

# Exercise Week 2

```{r}
rm(list=ls())
library(tidyverse)
library(sf)
library(terra)
library(lubridate)
```

# Task 1
```{r}
ws <- read_delim("wildschwein_BE_2056.csv")

ws_sf <- st_as_sf(ws, coords = c("E", "N"), crs = 2056, remove = FALSE)
```



--------------------------------------------------------------------------------



# Task 2 - Getting an overview

Calculate the time difference between subsequent rows 

```{r}
sum(is.na(ws_sf$DatetimeUTC)) # no na's

ws_sf <- group_by(ws_sf, TierID)

ws_sf <- mutate(ws_sf, timelag = as.integer(difftime(lead(DatetimeUTC), DatetimeUTC, units = "secs")))

# NA's ?
summary(ws_sf$timelag)
# 3 NA's, as expected from shifts in 3 groups
```


    How many individuals were tracked?
    For how long were the individuals tracked? Are there gaps?
    Were all individuals tracked concurrently or sequentially?


```{r}
ggplot(ws_sf, aes(x = DatetimeUTC, y = TierID)) +
    geom_point()
```
- 3 Animals were tracked over a period of approx. 8 months, with one individual being tracked for approx. 1 year. 
- there seem to be no gaps
- they were tracked concurrently


    What is the temporal sampling interval between the locations?

```{r}
range(ws_sf$timelag)
nrow(filter(ws_sf, timelag >= 27000))

ws_sf %>% 
    filter(timelag <= 27000) %>%
    ggplot(aes(x = timelag)) +
    geom_histogram(binwidth = 60) +
    scale_y_log10()

# for visualization purpose 8 timelag values above 27000 were excluded in this histogram

```

-> temporal sampling intervals are distributed across a range between 12
& 60367 seconds, with some peaks between 0 & 6000 seconds and another large peak around 10000 seconds




--------------------------------------------------------------------------------



# Task 3 - Deriving movement parameters I: Speed

So far our trajectories only consist of a list of time-stamped spatial locations. So let’s calculate the animal’s steplength based on the Euclidean distance between two subsequent locations.


```{r}
ws_sf$steplength <- sqrt(((ws_sf$E - lead(ws_sf$E))**2) + ((ws_sf$N - lead(ws_sf$N))**2)) 

summary(ws_sf$steplength)
```


```{r}
ws_sf$speed <- (ws_sf$steplength / ws_sf$timelag)

summary(ws_sf$speed)
```

--> The speed unit should be in meters/seconds (m/S)



--------------------------------------------------------------------------------



# Task 4

```{r}

```



```{r}

```



```{r}

```



```{r}

```



```{r}

```



```{r}

```



```{r}

```



```{r}

```



```{r}

```



```{r}

```



```{r}

```



```{r}

```




